### ISSUE TITLE
urllib2.HTTPError: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by lucas03** [mouuff/mtranslate#1]
Hi,
Any idea, why am I getting error 503 on my vps server as well as on my openshift account? On localhost it works fine.

**Comment by mouuff** [comment]
No idea

**Comment by Deph0** [comment]
@lucas03 Could be blacklisted by google, try going to the webpage manually in a browser. 

Thanks for this script, @mouuff, after google decided to block the /translate_a/ url on me, this saved me from hours of searching for a different approach while keeping it simple.

**Comment by lucas03** [comment]
yep, since google translate has paid service, google keeps large database of public ips that are blacklisted. Also if you find working proxy, after few translations proxy is temporarily blocked. Thanks for code anyway.
