### ISSUE TITLE
can't insert inside of facebook chatbots 

### ISSUE THREAD

**Issue by omarhassanatef** [mouuff/mtranslate#13]
from mtranslate import translate
x = message_text
def main():
    to_translate = x
    x1 =(translate(to_translate))
    x2 =(translate(to_translate, 'ar'))

    x = x1 + "     " + x2

if __name__ == '__main__':
    main()

**Comment by mouuff** [comment]
If you are using windows:

you can try to run this command (in the cmd) before launching the script:
`chcp 1256`
It will change windows page code for arab

you can get rid of the error (but it will not fix everything) : 
`x1.encode(sys.stdout.encoding, errors='replace')`

I also heard about a module called "win-unicode-console" for windows (install with pip) but I did not try it

**Comment by omarhassanatef** [comment]
i am using python 3.4 

its working on windows , but when i try to insert it in my facebook messenger chatbot online , nothing happens 

can you help?

**Comment by mouuff** [comment]
I can't help without informations, (like errors code, sample code to highlight the problem)

**Comment by omarhassanatef** [comment]
import os
import sys
import json
import mtranslate

import requests
from flask import Flask, request

app = Flask(__name__)


@app.route('/', methods=['GET'])
def verify():
    # when the endpoint is registered as a webhook, it must echo back
    # the 'hub.challenge' value it receives in the query arguments
    if request.args.get("hub.mode") == "subscribe" and request.args.get("hub.challenge"):
        if not request.args.get("hub.verify_token") == os.environ["VERIFY_TOKEN"]:
            return "Verification token mismatch", 403
        return request.args["hub.challenge"], 200

    return "Hello world", 200


@app.route('/', methods=['POST'])
def webhook():
    message_text = ""
    # endpoint for processing incoming messaging events

    data = request.get_json()
    log(data)  # you may not want to log every incoming message in production, but it's good for testing

    if data["object"] == "page":

        for entry in data["entry"]:
            for messaging_event in entry["messaging"]:

                if messaging_event.get("message"):  # someone sent us a message

                    sender_id = messaging_event["sender"]["id"]        # the facebook ID of the person sending you the message
                    recipient_id = messaging_event["recipient"]["id"]  # the recipient's ID, which should be your page's facebook ID
                    message_text = messaging_event["message"]["text"]  # the message's text
                    #x=  message_text["message"]

                    send_message(sender_id, message_text)

                if messaging_event.get("delivery"):  # delivery confirmation
                    pass

                if messaging_event.get("optin"):  # optin confirmation
                    pass

                if messaging_event.get("postback"):  # user clicked/tapped "postback" button in earlier message
                    pass

    return "ok", 200





#translation

from mtranslate import translate

def main():
    to_translate = message_text
    x1 =(translate(to_translate))
    x2 =(translate(to_translate, 'ar'))

    message_text = x1 + "     " + x2

if __name__ == '__main__':
    main()

# end of translation code 



def send_message(recipient_id, message_text):

    log("sending message to {recipient}: {text}".format(recipient=recipient_id, text=message_text))

    params = {
        "access_token": os.environ["PAGE_ACCESS_TOKEN"]
    }
    headers = {
        "Content-Type": "application/json"
    }
    data = json.dumps({
        "recipient": {
            "id": recipient_id
        },
        "message":{
            "text":  message_text
        }
    })
    r = requests.post("https://graph.facebook.com/v2.8/me/messages", params=params, headers=headers, data=data)
    if r.status_code != 200:
        log(r.status_code)
        log(r.text)


def log(message):  # simple wrapper for logging to stdout on heroku
    print str(message)
    sys.stdout.flush()


if __name__ == '__main__':
    app.run(debug=True)

**Comment by mouuff** [comment]
could you paste your code on gist.github.com or pastebin.com ?

**Comment by omarhassanatef** [comment]
this is my full chatbot code , its supposed to receive the user messsage ( text_message ) and then using your mtranslate , translates it and re-set the value of text_message to the new translation and then re send it to the user 

but it just stops responding 
can you see something wrong ?

**Comment by mouuff** [comment]
I can't use your code if you don't paste it in a proper way github comments syntax breaks it

**Comment by omarhassanatef** [comment]
https://github.com/omarhassanatef/chatbot

sorry im new to github :D , here it is

**Comment by mouuff** [comment]
It is not working because message_text is not defined

**Comment by mouuff** [comment]
Update?

**Comment by omarhassanatef** [comment]
the issue was with that the text was ascii code , it needs to be UTF-8 , it works perfectly
