### ISSUE TITLE
HTTPError: HTTP Error 413: Request Entity Too Large

### ISSUE THREAD

**Issue by karimkhanp** [mouuff/mtranslate#15]
Hello,
Thanks for this library. I got this error when characters lenth is 6000. I tried with 3000 characters but still same error. What is the character limit here?

**Comment by mouuff** [comment]
I use http GET requests to send the data, so there is indeed a limitation:
https://stackoverflow.com/questions/266322/is-there-a-limit-to-the-length-of-a-get-request
I tried with 8000 characters and I have no issues.
