### ISSUE TITLE
Google API

### ISSUE THREAD

**Issue by mvpcom** [mouuff/mtranslate#16]
Hi, is there any way to upgrade MTranslate for using Google API codes (https://cloud.google.com/translate/docs/auth#using_an_api_key)? For example, Because the base link is a little bit different with the primary base link in your code,  I'm not sure if I change the base link what will happen? Google API's base link is https://translation.googleapis.com/language/translate/v2?key=YOUR_API_KEY. Do you have any idea? Thanks.

**Comment by mouuff** [comment]
The goal of mtranslate is to not use keys, there is no way it would work just by changing base link.

**Comment by mouuff** [comment]
No this wouldn't work so easily
I don't see why you want to do that.

**Comment by mvpcom** [comment]
Yes, you're right, but the problem is Google will limit the requests. I have to translate more than 4 million sentences with Google Translate, and the speed is insufficient. Approximately, 200000 sentences per day :(

**Comment by mouuff** [comment]
Then yes, you should probably go for the official API, you should find one pretty easily.
But I believe you will have to pay for that much requests per day.
Otherwise you could eventually try with proxies but I wouldn't recommend it if you plan to do that much requests
