### ISSUE TITLE
converting to ipynb file

### ISSUE THREAD

**Issue by sharundra** [mouuff/mtranslate#17]
hey,
is there a way to convert this repository to a single ipynb file...

**Comment by mouuff** [comment]
I don't know, I have never used ipynb nor know what it does.
This project only uses standard python libraries and the project is really small (the algorithm is in core.py actually), so I think you can give it a try.

**Comment by sharundra** [comment]
yeah, it works fine with standard python libraries but actually for much interactive interface, I wanted to use this repository in jupyter notebook (ipynb files). BTW thanks for your quick response!!

**Comment by mouuff** [comment]
maybe this can help you
https://github.com/sklam/py2nb
