### ISSUE TITLE
Parameter Adjustment Needed

### ISSUE THREAD

**Issue by weidenrinde** [mouuff/mtranslate#19]
Google changed it's parameters and the result page sometimes looks different. The following changes are necessary:

1.) ht -> tl
`base_link = "http://translate.google.com/m?tl=%s&sl=%s&q=%s"`

2) the regex needs to test for two classes and may include newlines
`expr = r'(?s)class="(?:t0|result-container)">(.*?)<'`

**Comment by mouuff** [comment]
Thank you for your support! Changes have been pushed!
