### ISSUE TITLE
Error 400 while using on a google colab. 

### ISSUE THREAD

**Issue by miguelpetete** [mouuff/mtranslate#24]
I am having a http error 400 while I'm trying to use it for translating a big .csv archive in google colab.

**Comment by miguelpetete** [comment]
<img width="1326" alt="Captura de pantalla 2023-03-30 a las 19 18 10" src="https://user-images.githubusercontent.com/36732119/228914728-45099dff-0a46-42b8-b379-dd98f1e3600f.png">

**Comment by mouuff** [comment]
What is the value of "cell"?

**Comment by miguelpetete** [comment]
Cell is each of the cells that we could find in a row of a .csv archive. This archives are finally as a .xml archive of microsoft excel that contains information in each cell

**Comment by miguelpetete** [comment]
Is there any limitations on how much translations you could send to the google api?

**Comment by mouuff** [comment]
400 means bad request, not "too many requests"

**Comment by mouuff** [comment]
My guess is that the value of "cell" is not a string
