### ISSUE TITLE
use POST instead of GET request

### ISSUE THREAD

**Issue by eadmaster** [mouuff/mtranslate#3]
Hi, i've tried the python script and it is still working pretty well.

Is it possible to send POST requests to translate longer text?

see:
https://github.com/soimort/translate-shell/issues/30
https://www.filosophy.org/post/36/crossdomain_post_requests_to_google_translate_v2/

**Comment by mouuff** [comment]
Fell free to make pull request, I m sorry I have no time for that this month

**Comment by eadmaster** [comment]
Nevermind, i've switched to [a bash script that does the job just fine](http://pastebin.com/SVs62qPH).

**Comment by Epigene** [comment]
I have not tested this, but I hear that making a POST with custom headers may do the trick.

Pseudocode

``` rb
response = RestClient::Request.execute(url: url, method: :post, verify_ssl: false, headers: {"X-HTTP-Method-Override" => "GET"})
```

**Comment by mouuff** [comment]
I checked, there is indeed a problem with large texts today, thanks for the report
